version: '3.6'
services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: find_wifi_mysql
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: find_wifi_db

  # API Spec
  redoc:
    image: redocly/redoc
    container_name: find_wifi_redoc
    ports:
      - 1324:80
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      SPEC_URL: openapi.yml
